apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestoperac-deployment
spec:
  selector:
    matchLabels:
      app: gestoperac
  template:
    metadata:
      labels:
        app: gestoperac
    spec:
      containers:
      - name: gestoperac
        image: ispy02/gestoperac:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 80
        env:
          - name: MongoDBSettings__Host
            value: mongodb-service
          - name: MongoDBSettings__Password
            valueFrom:
              secretKeyRef:
                name: gestoperac-secrets
                key: mongodb-password
        livenessProbe:
          httpGet:
            path: "/health/live"
            port: 80
        readinessProbe:
          httpGet:
            path: "/health/ready"
            port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: gestoperac-service
spec:
  type: LoadBalancer
  selector:
    app: gestoperac
  ports:
  - port: 80
    targetPort: 80
